.catalog:
  name: Arce Gitlab Community
  version: 9.5.10-ce.0
  description: |
    Gitlab CE is a free GitHub alternative
  minimum_rancher_version: v0.56.0
  maintainer: "Alexis Ducastel <alexis@ducastel.net>"
  uuid: gitlab-0
  questions:
    - variable: "gitlab_hostname"
      description: "Gitlab hostname (without uri scheme http:// or https://)"
      label: "Hostname:"
      required: true
      default: "git.arce.lan"
      type: "string"
    - variable: "registry_gitlab_hostname"
      description: "Registry Gitlab hostname (without uri scheme http:// or https://)"
      label: "Registry hostname:"
      required: true
      default: "registry.arce.lan"
      type: "string"
    - variable: "gitlab_omnipus_prefix"
      label: "Gitlab external_url prefix:"
      description: |
        This is needed for the docker-compose file to set the correct external_url
      default: 'http://'
      required: true
      type: "enum"
      options:
        - 'http://'
        - 'https://'
    - variable: "volumedriver"
      description: "Choose the Volume Driver being used.(Option: local or rancher-nfs)"
      label: "Volume Driver:"
      required: true
      default: local
      type: "enum"
      options:
        - local
        - rancher-nfs
    - variable: "gitlab_gmail_username"
      description: "Gmail account for SMTP"
      label: "Account Name:"
      required: true
      default: "username@gmail.com"
      type: "string"
    - variable: "gitlab_gmail_password"
      description: "Gmail account for SMTP"
      label: "Password:"
      required: true
      default: "password"
      type: "string"

gitlab-server:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 3000
    healthy_threshold: 2
