openhab:
    image: openhab/openhab:2.1.0-amd64
    ports:
        - 8080:8080
        - 8443:8443
    environment:
        EXTRA_JAVA_OPTS: ””
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8
        LANGUAGE: en_US.UTF-8
        OPENHAB_HTTP_PORT: 8080
        OPENHAB_HTTPS_PORT: 8443
#        USER_ID=9001
#    external_links:
#        - ${database_link}:database
#        - ${redis_link}:redis
#    extra_hosts:
#        - "database:${database_IP}"
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
        - /opt/openhab/conf:/net/tardis/sonic/rancher/openhab/conf 
        - /opt/openhab/userdata:/net/tardis/sonic/rancher/openhab/userdata 
        - /opt/openhab/addons:/net/tardis/sonic/rancher/openhab/addons 
        - /opt/openhab/.java:/net/tardis/sonic/rancher/openhab/.java 
