grafana:
    image: grafana/grafana:latest
#    ports:
#        - ${http_port}:3000
    environment:
        GF_SECURITY_ADMIN_USER: ${admin_username}
        GF_SECURITY_ADMIN_PASSWORD: ${admin_password}
        GF_SECURITY_SECRET_KEY: ${secret_key}
        GF_INSTALL_PLUGINS: ${plugins}
        GF_SESSION_PROVIDER: "redis"
        GF_SESSION_PROVIDER_CONFIG: "addr=redis:6379,pool_size=100,db=grafana"
        GF_DATABASE_TYPE: "postgres"
        GF_DATABASE_HOST: "database:5432"
        GF_DATABASE_NAME: "grafana"
        GF_DATABASE_USER: "grafana"
        GF_DATABASE_PASSWORD: "grafana"
#        GF_SERVER_PROTOCOL: ${proxy_scheme}
#        GF_SERVER_PROTOCOL: "http"
        GF_SERVER_DOMAIN: ${proxy_name}
#        GF_SERVER_HTTP_PORT: ${proxy_port}
    external_links:
        - ${database_link}:database
        - ${redis_link}:redis
#    volumes:
#        - ${grafana_home}:/var/lib/grafana
