.catalog:
  name: "OpenFaaS-Arce"
  version: "v0.0.2"
  description: "Enable Rancher as a backend for Functions as a Service (OpenFaaS)"
  uuid: "openfaas-0"
  minimum_rancher_version: v1.5.0
  questions:
     - variable: "CATTLE_URL"
       description: "The v2-beta Rancher Server Endpoint. e.g. https://try.rancher.com/v2-beta"
       label: "Rancher Server Endpoint URL."
       required: true
       type: "string"
     - variable: "CATTLE_ACCESS_KEY"
       description: "The Rancher API Access Key"
       label: "API Access Key"
       required: true
       type: "string" 
     - variable: "CATTLE_SECRET_KEY"
       description: "The Rancher API Secret Key"
       label: "API Secret Key"
       required: true
       type: "string" 
     - variable: "FUNCTION_STACK_NAME"
       default: "faas-functions"
       description: "The stack name faas functions will be deployed to. If it doesn't exist, it will be created automatically."
       label: "Functions Stack Name"
       required: true
       type: "string" 

version: '2'
services:
  prometheus:
    scale: 1
    start_on_create: true
  faas-rancher:
    scale: 1
    start_on_create: true
  gateway:
    scale: 1
    start_on_create: true
  alertmanager:
    scale: 1
    start_on_create: true
