name: "Gallery" # Name of the Catalog Entry
description: |
  "Apache for Gallery" # Description of the Catalog Entry
version: "0.1" # Version of the Catalog to be used
category: # Category to be used for searching catalog entries
maintainer: # The maintainer of the catalog entry
license: # The license
projectURL: "https://github.com/bordershot/rancher-arce.git"
